"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
const WeaponPower_1 = require("./bassClass/WeaponPower");
const ExplorationShip_1 = require("./ships/ExplorationShip");
const Fighter_1 = require("./ships/Fighter");
const MultiPurposeShip_1 = require("./ships/MultiPurposeShip");
const TransportShip_1 = require("./ships/TransportShip");
const Fleet_1 = require("./fleet/Fleet");
const combatShips = [];
const exploratoryShips = [];
const carrierShips = [];
const colectionShip = [];
const kinetic = new WeaponPower_1.WeaponPower('Kinetic Cannons', 45);
const torpedoes = new WeaponPower_1.WeaponPower('Torpedoes and Guided Missiles', 55);
const xwing = new Fighter_1.Fighter('X-Wing', torpedoes);
const tie = new Fighter_1.Fighter('TIE Fighter', kinetic);
const emma = new TransportShip_1.TransportShip('Emma Marsk');
const goliath = new TransportShip_1.TransportShip('Goliath II');
const millennium = new ExplorationShip_1.ExplorationShip('Millennium Falcon');
const stellaris = new ExplorationShip_1.ExplorationShip('Stellaris');
const nostromo = new MultiPurposeShip_1.MultiPurposeShip('Nostromo');
colectionShip.push(xwing);
colectionShip.push(tie);
colectionShip.push(emma);
colectionShip.push(goliath);
colectionShip.push(millennium);
colectionShip.push(stellaris);
colectionShip.push(nostromo);
const colectionFleet = new Fleet_1.Fleet(colectionShip);
//Exiba todas as naves;
// colectionFleet.showFleet();
//Realize pelo menos um combate;
// startCombat(xwing, emma);
//Transporte algumas cargas;
// transportCargo(goliath, 5);
//Realize uma exploração;
// performExploration(stellaris, 'Marte');
//Cause dano em uma nave;
// tie.attack(millennium);
// //Repare uma nave;
// //-Usando a minha interface Repairable;
// repairObject(tie);
// //-Usando o meu método que está na minha classe SpaceCraft.
// console.log(emma.repair() ? 'Spaceship being repaired.' : 'Living life to the fullest.');
//Recupere combustível;
// console.log(stellaris.refuel() ? 'Spacecraft refueling' : 'Gasoline below 0 or above 100');
//Liste as naves de combate;
console.log('\nNAVES DE COMBATE\n');
colectionFleet.getCombatShip().forEach((c, i) => {
    console.log(i + 1 + ' - ' + c.getName());
});
console.log('\nNAVES DE TRANSPORTE\n');
colectionFleet.getCargoShip().forEach((c, i) => {
    console.log(i + 1 + ' - ' + c.getName());
});
console.log('\nAVES DE EXPLORACAO\n');
colectionFleet.getExplorationShip().forEach((e, i) => {
    console.log(i + 1 + ' - ' + e.getName());
});
