"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
const WeaponPower_1 = require("./bassClass/WeaponPower");
const ExplorationShip_1 = require("./ships/ExplorationShip");
const Fighter_1 = require("./ships/Fighter");
const MultiPurposeShip_1 = require("./ships/MultiPurposeShip");
const TransportShip_1 = require("./ships/TransportShip");
const Function_1 = require("./function/Function");
const combatShips = [];
const exploratoryShips = [];
const carrierShips = [];
const colectionShip = [];
const kinetic = new WeaponPower_1.WeaponPower('Kinetic Cannons', 45);
const torpedoes = new WeaponPower_1.WeaponPower('Torpedoes and Guided Missiles', 55);
const fighter1 = new Fighter_1.Fighter('X-Wing', torpedoes);
const fighter2 = new Fighter_1.Fighter('TIE Fighter', kinetic);
const transportShip1 = new TransportShip_1.TransportShip('Emma Marsk');
const transportShip2 = new TransportShip_1.TransportShip('Goliath II');
const exploratory1 = new ExplorationShip_1.ExplorationShip('Millennium Falcon');
const exploratory2 = new ExplorationShip_1.ExplorationShip('Stellaris');
const multiPurpose = new MultiPurposeShip_1.MultiPurposeShip('Nostromo');
colectionShip.push(fighter1);
colectionShip.push(fighter2);
colectionShip.push(multiPurpose);
colectionShip.push(exploratory1);
colectionShip.push(exploratory2);
colectionShip.push(multiPurpose);
colectionShip.push(transportShip1);
colectionShip.push(transportShip2);
colectionShip.push(multiPurpose);
// startCombat(multiPurpose, fighter2);
// performExploration(exploratory1, 'Lua');
// performExploration(multiPurpose, 'Jupiter');
// repairObject(fighter2);
// const colectionFleet: Fleet = new Fleet(colectionShip);
// colectionFleet.showFleet();
(0, Function_1.startCombat)(fighter1, transportShip2);
